<?php
$z[0]=Array("noteinfo","",0,211);
$z[0][4]=array();
$z[0][4]['notename']="采集八卦星";
$z[0][4]['channelid']="1";
$z[0][4]['macthtype']="string";
$z[0][4]['refurl']="http://www.baguaxing.com/bagua/2017062099926.shtml";
$z[0][4]['sourcelang']="utf-8";
$z[0][4]['cosort']="asc";
$z[0][4]['isref']="no";
$z[0][4]['exptime']="10";
$z[0][4]['usemore']="0";
$z[1]=Array("listrule","\n    {dede:addurls}{/dede:addurls}\n    {dede:batchrule}{/dede:batchrule}\n    {dede:regxrule}{/dede:regxrule}\n    {dede:areastart}news-col-main{/dede:areastart}\n    {dede:areaend}new-page{/dede:areaend}\n",212,630);
$z[1][4]=array();
$z[1][4]['sourcetype']="batch";
$z[1][4]['rssurl']="http://";
$z[1][4]['regxurl']="http://www.baguaxing.com/bagua/list_(*).shtml";
$z[1][4]['startid']="1";
$z[1][4]['endid']="10";
$z[1][4]['addv']="1";
$z[1][4]['urlrule']="area";
$z[1][4]['musthas']="";
$z[1][4]['nothas']="";
$z[1][4]['listpic']="1";
$z[1][4]['usemore']="0";

?>