{dede:noteinfo notename="采集八卦星" channelid="1" macthtype="string"
refurl="http://www.baguaxing.com/bagua/2017062099926.shtml" sourcelang="utf-8" cosort="asc" isref="no" exptime="10" usemore="0" /}

{dede:listrule sourcetype="batch" rssurl="http://" regxurl="http://www.baguaxing.com/bagua/list_(*).shtml"
startid="1" endid="10" addv="1" urlrule="area"
 musthas="" nothas="" listpic="1" usemore="0"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<div class="news-cont">{/dede:areastart}
    {dede:areaend}</div> <div class="new-page">{/dede:areaend}
{/dede:listrule}
