<?php
$z[0]=Array("global","",97,122);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",184,209);
$z[1][4]=array();
$z[1][4]['name']="cfg_cmsurl";
$z[2]=Array("global","",377,404);
$z[2][4]=array();
$z[2][4]['name']="cfg_basehost";
$z[3]=Array("global","",416,448);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",495,521);
$z[4][4]=array();
$z[4][4]['name']="cfg_webname";
$z[5]=Array("global","",836,861);
$z[5][4]=array();
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("channel","\r\n      	<li><a href='[field:typeurl/]' [field:rel/]><span>[field:typename/]</span></a></li>\r\n      	",901,1144);
$z[6][4]=array();
$z[6][4]['type']="top";
$z[6][4]['row']="10";
$z[6][4]['currentstyle']="<li class='hover'><a href='~typelink~' ~rel~><span>~typename~</span></a></li>";
$z[7]=Array("global","",1236,1261);
$z[7][4]=array();
$z[7][4]['name']="cfg_cmsurl";
$z[8]=Array("tag","\r\n            <li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",2069,2199);
$z[8][4]=array();
$z[8][4]['row']="10";
$z[8][4]['getall']="1";
$z[8][4]['sort']="month";

?>